add stats-service
LinarJC/explore-with-me pull request #1
Opened 2023-02-03 07:48 UTC by LinarJC

2023-02-03 08:33 UTC, LinarJC commented
Приветствую) реализация сервиса статистики на проверку

2023-02-03 17:01 UTC, EugeneLenkevich requested changes
Привет, Линар, спасибо за PR

В целом все здорово, единственное, может я и ошибаюсь, но, вроде как, на этом этапе надо еще реализовать http-клиент для нашего контроллера и что-то я его не вижу нигде, посмотри пожалуйста :)

PS
если есть желание то можешь попробовать Feign
https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/

То есть реализуется интерфейс? наподобие репозиториев, тольк он http-запросы отправляет. Далее его можно импортировать в других сервисах и использовать для того чтобы обращаться к нашему, получается что это контракт нашего сервиса :)

2023-02-03 17:01 UTC, EugeneLenkevich commented on stats-service/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +            @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
Давай попробуем настроить фоматы даты и времени глобально, чтобы не приходилось вот так везде аннотациями это указывать :)

https://www.baeldung.com/spring-boot-formatting-json-dates

2023-02-05 11:58 UTC, LinarJC commented on stats-service/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +            @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
Попробовал способ с указанием в параметра в properties, но он оказался не рабочим, потом понял, что пока им класс  localdatatime не поддерживается, второй способ с аннотациями тоже не подошел, так как параметры с форматом находятся в методе

2023-02-05 12:04 UTC, LinarJC commented on stats-service/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +            @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
с Feight попробовал, но судя по логам, возникли проблемы с конфигурацией. Из за ограниченности времени на изучение и допиливание интеграции инструмента, принял решение сделать привычным путем =)

2023-02-05 12:17 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-02-24 08:52 UTC, merged