main svc
LinarJC/explore-with-me pull request #4
Opened 2023-02-16 19:01 UTC by LinarJC

Добавлен main service

2023-02-17 05:06 UTC, EugeneLenkevich requested changes
Привет, Линар, спасибо за PR

На самом деле все замечательно. Единственное, присутствует некоторое смешение слоев, отметил момент про HTTP-статусы на уровне сервисов. Все таки мы ожидлаем что бизнес-слой(слой сервисов) будет выкидывать бизнес-исключения, да и работать может в среде без http вовсе, допустим есть только брокер сообщений. Еще отметил пару мест, которые можно сделать чуточку оптимальнее :)

2023-02-17 05:06 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +        if (!categoryRepository.existsById(id)) {
Вроде как это же можно было сделать  одним запрсом, в случае если categoryRepository.getReferenceById(id) ничего не нашел (null или Optional.empty(), если хочется) то выкидывать исключение  :)

2023-02-17 05:06 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Uncorrected request");
Тут у нас идет смешение слоев. 
1. Сервис ничего не знает про http и про коды статусов 
2. Сама логика - у нашей бизнес сущности на хватает аттрибута, а пользователь получает отлуп из глубины сервиса а том что запрос неправильный, будет ли ему понятно что вообще происходит, особенно если учесть что код он не видит? :)
3. Сервис может вызвать не только контроллер, а предположим слушатель сообщений (MQ), там http вообще нет :)

Мне каежтся тот логичнее выкинуть ValidationException в сообщении которого указать причину (пустое поле) :)

2023-02-17 05:06 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +        if (eventRepository.findEventsByCategory(catId).size() > 0) {
eventRepository.findEventsByCategory(catId).size()

Вот тут мы вытаскиваем все записи из БД чтобы узнать их колдичество, а если их там пять миллиардов :)
В общем это считается плохой практикой, попробуй сделать count- запрос (аналогично exists-запросам которые ты уже используешь)

https://stackoverflow.com/questions/10696490/does-spring-data-jpa-have-any-way-to-count-entites-using-method-name-resolving

2023-02-17 05:06 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.CONFLICT, "You can't delete a category with related events");
Опять таки, несоответствие на уровне бизнес лгики порождает HttpStatus.CONFLICT, что есть техническая ошибка урновня передачи данных (касательно на самом деле всех http-ответов) :)

2023-02-17 05:06 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/user/service/UserServiceImpl.java
> +    public UserDto saveUser(NewUserDto newUserDto) {
А давай ка еще над все методы, которые изменяют данные (insert, update и delete) будем оформлять как логические транзакции, так будет правильнее. То есть добавим аннотацию @Transactional над ними

2023-02-17 05:06 UTC, EugeneLenkevich commented on stats-service/stats-server/src/main/java/ru/practicum/repository/StatsRepository.java
> +    List<ViewStatsDto> getStats(LocalDateTime start, LocalDateTime end, Set<String> uris);
Все верно, за один запрос все данные вытаскиваешь :)

2023-02-18 14:15 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +        if (!categoryRepository.existsById(id)) {
Пробовал сначала через categoryRepository.getReferenceById(id) подставит конструкцию if потом понял, что база выдает исключение при таком запросе ничего не возвращая, сделал в итоге через try catch

2023-02-18 14:16 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +        if (eventRepository.findEventsByCategory(catId).size() > 0) {
Вытащил количество через запрос

2023-02-18 14:16 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/user/service/UserServiceImpl.java
> +    public UserDto saveUser(NewUserDto newUserDto) {
Добавил аннотации @transactional

2023-02-18 14:17 UTC, LinarJC commented on stats-service/stats-server/src/main/java/ru/practicum/repository/StatsRepository.java
> +    List<ViewStatsDto> getStats(LocalDateTime start, LocalDateTime end, Set<String> uris);
Спасибо)

2023-02-18 14:17 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.CONFLICT, "You can't delete a category with related events");
сделал отработку исключений через ValidationException

2023-02-18 14:18 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Uncorrected request");
Согласен) сделал отработку исключений через ValidationException

2023-02-18 16:40 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +        if (!categoryRepository.existsById(id)) {
Все равно лучше чем два зпроса в БД, пусь так будет :)

2023-02-18 16:46 UTC, EugeneLenkevich requested changes
Привет, спасибо за доработку, все гут, единственное давай исключения доделаем немножко :)

2023-02-18 16:46 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +            throw new ValidationException("Empty field",
Не совсем :)

Имею в виду вот такое 

`throw new ValidationException("Не укзаано наименование категории")`

Не надо тут добавлять new ResponseStatusException(HttpStatus... сетевые ошибки -  это уже уровень контроллеров. Да и вообще, в таком случае, имею в виду при исключительной ситуации на уровне сервиса, все будут ждать что контроллер вернет код 500. В общем, это все произойдет автоматически, не надо тут ничего дополнительно

2023-02-18 19:17 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +            throw new ValidationException("Empty field",
Понял) убрал ResponseStatusException из сервиса

2023-02-19 03:39 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-02-24 08:52 UTC, merged