add feature comments
LinarJC/explore-with-me pull request #6
Opened 2023-02-19 21:43 UTC by LinarJC

Привет) Добавлена фича comments

2023-02-20 16:43 UTC, EugeneLenkevich requested changes
Привет, Линар, спасибо за PR

Ну что, это дипломная работа, в целом все здорово, но давай мы еще тут понаводим красоту :)
Я отметил коментариями моменты, посмотри, пожалуйста
 - не стоит в контроллерах оставлять бизнес-логику, там только обработка запросов. А еще ты же можешь использовать разные типы исключений и через ControllerAdvice присвоить им соответсвующие http-коды 
 - проверь наименования методов в сервисах, попробу. сделать имена единообразно (в целом так и есть), пюс можно в них не обязательно дублировать наименование сущности, а то получается масло-маслянное
 - посмотри везде ли надо руками писать запросы  в репозиториях, спринг их умеет генерировать самостоятельно через имена методов. Ты используешь оба подхода, но руками ж и дольше писать и кода больше, то есть другому разработчике дополнительно разбираться ну и ошибиться проще :)

В целом, конечно, ты большой молодец, ты дошел до финишной прямой, ты крут, удачи!

2023-02-20 16:43 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/controller/CategoryAdminController.java
> +        if (categoryRepository.existsCategoryByName(categoryDto.getName())) {
По своей сути контроллер только обрабатывает (маршрутизирует сервисам) запросы, а тут же в контроллере выполняется бизнес-логика, ее лучше перенести в сервис, иначе логика размазывается по нескольким классам, в общем так не рекомендуют делать :)

2023-02-20 16:43 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/controller/CategoryAdminController.java
> +        if (categoryDto.getName() == null) {
Это же можно сделать через аннотации @NotBlank :)

2023-02-20 16:43 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/controller/CategoryAdminController.java
> +            throw new ValidationException("This name is exist",
Кроме того что логика в контроллере. Не уверен что стоит вкладывать одно исключение в другое. Достаточно кидать (из сервиса конечно) ValidationException

Плюс, контроллер вернет ошибку 500 (Internal Server Error.)
HttpStatus.CONFLICT - вооще не уверен что пустое поле сущности -  это конфликт
https://developer.mozilla.org/ru/docs/Web/HTTP/Status/409

А, вообще, если уж хочется сделать такую обработку ошибок, то стоит это делать централизовано, примерно вот так
https://stackoverflow.com/questions/24292373/spring-boot-rest-controller-how-to-return-different-http-status-codes

2023-02-20 16:43 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryService.java
> +    List<CategoryDto> getCategories(Integer from, Integer size);
Класс нащывается CategoryService, из названия слежует что он управляет категориями, в именах методов уже можно это не укзаывать, так будет короче и проще для воспрития 
get()
save()

2023-02-20 16:43 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryService.java
> +    CategoryDto patchCategory(Long catId, NewCategoryDto categoryDto);
patchCategory
Мне кажется или тут идет привязка к именам http-методов? :)
Так не стоит делать, наш сервис не должен знать ничегопро откуда его вызыват, пусть лучше называется например update :)

2023-02-20 16:43 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +        } catch (ValidationException exception) {
А зачем ловить исклчение  чтобы его же перепроинуть дальше, думаю можно вовсе убрать тут try-catch :)

2023-02-20 16:43 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/comment/repository/CommentRepository.java
> +    Comment findCommentByUserIdAndEventId(Long userId, Long eventId);
Запрос руками можно не писать, достаточно вот так его назвать и все должно заработать автоматически :)

Comment findByUserIdAndEventId(Long userId, Long eventId);

2023-02-20 16:43 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/comment/service/CommentService.java
> +    List<CommentDto> getCommentsByUserId(Long userId);
Оять таки в методах можно уже не указывать comment :)

2023-02-20 16:43 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/request/service/RequestServiceImpl.java
> +    public ParticipationRequestDto saveRequest(Long userId, Long eventId) {
А давай ка еще над все методы, которые изменяют данные (insert, update и delete) будем оформлять как логические транзакции, так будет правильнее. То есть добавим аннотацию @Transactional над ними

2023-02-20 16:43 UTC, EugeneLenkevich commented on stats-service/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +            @RequestParam @DateTimeFormat(pattern = DTFPattern) LocalDateTime start,
@DateTimeFormat(pattern = DTFPattern)

Давай попробуем настроить фоматы даты и времени глобально, чтобы не приходилось вот так везде аннотациями это указывать :)

https://www.baeldung.com/spring-boot-formatting-json-dates

2023-02-23 20:06 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/controller/CategoryAdminController.java
> +        if (categoryRepository.existsCategoryByName(categoryDto.getName())) {
Перенёс в сервис

2023-02-23 20:07 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/controller/CategoryAdminController.java
> +        if (categoryDto.getName() == null) {
Сделано

2023-02-23 20:08 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/controller/CategoryAdminController.java
> +            throw new ValidationException("This name is exist",
Сделал централизовано через @ControllerAdvice

2023-02-23 20:09 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryService.java
> +    List<CategoryDto> getCategories(Integer from, Integer size);
Упростил названия методов

2023-02-23 20:09 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryService.java
> +    CategoryDto patchCategory(Long catId, NewCategoryDto categoryDto);
Переименовал

2023-02-23 20:10 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/category/service/CategoryServiceImpl.java
> +        } catch (ValidationException exception) {
Убрал, это оказалось тоже лишним)

2023-02-23 20:11 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/comment/repository/CommentRepository.java
> +    Comment findCommentByUserIdAndEventId(Long userId, Long eventId);
Убрал ручные запросы, переименовал методы для автоматической отработки

2023-02-23 20:11 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/comment/service/CommentService.java
> +    List<CommentDto> getCommentsByUserId(Long userId);
Убрал)

2023-02-23 20:12 UTC, LinarJC commented on ewm-service/src/main/java/ru/practicum/ewmsvc/request/service/RequestServiceImpl.java
> +    public ParticipationRequestDto saveRequest(Long userId, Long eventId) {
Добавил аннотации @transactional

2023-02-23 20:14 UTC, LinarJC commented on stats-service/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +            @RequestParam @DateTimeFormat(pattern = DTFPattern) LocalDateTime start,
Убрал из контроллера, сделал глобально через application.properties

2023-02-23 20:16 UTC, LinarJC commented
Привет, Евгений) 
Спасибо за ревью, внёс правки по указанным замечаниям

2023-02-24 05:52 UTC, eugene-lenkevich approved these changes
Теперь все отлично, спасибо :)

2023-02-24 05:56 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmsvc/comment/repository/CommentRepository.java
> +    Comment findCommentByUserIdAndEventId(Long userId, Long eventId);
Как по мне так код стал гораздо короче и лучше выглядеть, солидней  :)

2023-02-24 08:52 UTC, merged